version: "3"

services:
  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rec-direc
    restart: always
    ports:
      - 4005:80
    networks:
      - rec-direc

networks:
  rec-direc:
    driver: bridge
